#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 2.0.{build}

skip_tags: false

#---------------------------------#
#    environment configuration    #
#---------------------------------#
os: Windows Server 2012

#---------------------------------#
#       build configuration       #
#---------------------------------#
platform: Any CPU

configuration: Release

build:
    parallel: true
    project: PSCredentialManager.sln

    verbosity: detailed

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test:
    assemblies:
        - PSCredentialManager.CmdletTests.dll
        - PSCredentialManager.ApiTests.dll

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#


#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
    provider: GitHub
    draft: true
    prerelease: false
    on:
        branch: master
        appveytor_repo_tag: true
